README.md
=> Fix typo in file path.

samples/mongodb/affinity/replica-set-affinity.yaml, samples/mongodb/persistent-volumes/replica-set-persistent-volumes.yaml, samples/mongodb/pod-template/replica-set-pod-template.yaml, samples/mongodb/pod-template/sharded-cluster-pod-template.yaml, samples/mongodb/pod-template/standalone-pod-template.yaml, samples/mongodb/podspec/replica-set-podspec.yaml
A few samples include an incorrectly keyed field, configMapName rather than configMapRef.  Small PR to adjust these.
=> updated configMapName to configMapRef

mongodb-enterprise.yaml
=> add "mongodb-enterprise-ops-manager" to mongodb-enterprise.yaml

dockerfiles/mongodb-enterprise-init-database/1.0.6/ubi/Dockerfile, dockerfiles/mongodb-enterprise-init-database/1.0.6/ubuntu/Dockerfile, dockerfiles/mongodb-enterprise-operator/1.14.0/ubi/Dockerfile, dockerfiles/mongodb-enterprise-operator/1.14.0/ubuntu/Dockerfile
This was fixed in enterprise repo in this PR: https://github.com/10gen/ops-manager-kubernetes/pull/2149
=> Fix missing Dockerfile updates

crds.yaml, dockerfiles/mongodb-agent/11.0.11.7036-1/ubi/Dockerfile, dockerfiles/mongodb-agent/11.0.11.7036-1/ubuntu/Dockerfile, dockerfiles/mongodb-enterprise-init-appdb/1.0.9/ubi/Dockerfile, dockerfiles/mongodb-enterprise-init-appdb/1.0.9/ubuntu/Dockerfile, dockerfiles/mongodb-enterprise-init-database/1.0.7/ubi/Dockerfile, dockerfiles/mongodb-enterprise-init-database/1.0.7/ubuntu/Dockerfile, dockerfiles/mongodb-enterprise-init-ops-manager/1.0.6/ubi/Dockerfile, dockerfiles/mongodb-enterprise-init-ops-manager/1.0.6/ubuntu/Dockerfile, dockerfiles/mongodb-enterprise-operator/1.15.0/ubi/Dockerfile, dockerfiles/mongodb-enterprise-operator/1.15.0/ubuntu/Dockerfile, mongodb-enterprise-openshift.yaml, mongodb-enterprise.yaml
This PR updates the yaml files for release 1.15.0
=> Updates yaml files for release 1.15.0

crds.yaml, mongodb-enterprise-openshift.yaml, mongodb-enterprise.yaml
These files were incorrectly updated and need to be reverted. They are used by PCT to detect if the a release branch has been merged already. The following PCT changes depend on this change to be able to proceed with the release:
- https://github.com/10gen/pct/pull/584
=> Reverts 1.15 update.

samples/mongodb_multi/replica-set-sts-override.yaml
=> Update Statefulset override sample for multi-cluster

dockerfiles/mongodb-agent/11.0.19.7094-1/ubi/Dockerfile, dockerfiles/mongodb-agent/11.0.19.7094-1/ubuntu/Dockerfile
=> HELP 34894 Add missing dockerfiles 3

tools/multicluster/Dockerfile
=> Add missing multicluster CLI Dockerfile

tools/multicluster/main.go
=> Fix Policy rules in the multi-cluster CLI tool

tools/multicluster/.goreleaser.yaml, tools/multicluster/setup_tls.sh
=> Add demo script for enabling TLS on mdbm resource

dockerfiles/mongodb-enterprise-operator/1.19.1/ubi/Dockerfile, dockerfiles/mongodb-enterprise-operator/1.19.1/ubuntu/Dockerfile
=> Fix dockerfile for 1.19.1 operator image

samples/ops-manager/ops-manager-backup.yaml
=> Fix type in s3 oplog store

mongodb-enterprise-multi-cluster.yaml
=> CLOUDP-176423 Added multi cluster kubectl example

.github/workflows/release-multicluster-cli.yaml
=> Update release-multicluster-cli.yaml to support manual release trigger

samples/appdb_multicluster/ops-manager-multi-cluster-appdb.yaml
=> Add AppDB multi-cluster sample

LICENSE
=> CLOUDP-240885 - update license

mongodb-enterprise-multi-cluster.yaml
=> fix multi-cluster example

mongodb-enterprise-openshift.yaml
=> Add missing sa

.evergreen.yml
Need to use dynamically generated github tokens due to the token deprecation.
=> Use dynamically generated github tokens
